import { useEffect, useState, type FormEvent } from "react";
import { generateCreative, getCreativeEngineHealth, getCreativeGeneration, getDashboard, listCreativeLibrary, type CreativeGeneration } from "./api";

export default function CreativeEngineWorkspace(){
 const [brandId,setBrandId]=useState("");const [brands,setBrands]=useState<Array<{id:string;name:string}>>([]);
 const [kind,setKind]=useState<"image"|"video">("image");const [objective,setObjective]=useState("Gerar demanda");const [prompt,setPrompt]=useState("");
 const [items,setItems]=useState<CreativeGeneration[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [configured,setConfigured]=useState(false);
 useEffect(()=>{void (async()=>{try{const [d,h]=await Promise.all([getDashboard(),getCreativeEngineHealth()]);setBrands(d.brands.map(b=>({id:b.id,name:b.name})));const id=d.brands[0]?.id||"";setBrandId(id);setConfigured(h.providers.some(p=>p.configured));if(id)setItems((await listCreativeLibrary(id)).items)}catch(e){setError(e instanceof Error?e.message:"Não foi possível abrir o Creative Engine.")}})()},[]);
 useEffect(()=>{if(brandId)void listCreativeLibrary(brandId).then(x=>setItems(x.items)).catch(()=>undefined)},[brandId]);
 useEffect(()=>{const pending=items.filter(x=>x.status==="queued"||x.status==="processing");if(!pending.length)return;const timer=window.setInterval(()=>{void Promise.all(pending.map(x=>getCreativeGeneration(x.id).catch(()=>x))).then(updated=>setItems(current=>current.map(item=>updated.find(x=>x.id===item.id)||item)))},2500);return()=>window.clearInterval(timer)},[items]);
 async function submit(e:FormEvent){e.preventDefault();setError("");setBusy(true);try{const created=await generateCreative({brandId,kind,objective,prompt,channel:"social",format:kind==="image"?"social":"vertical",provider:"higgsfield"});setItems(x=>[created,...x]);setPrompt("")}catch(e){setError(e instanceof Error?e.message:"Não foi possível gerar.")}finally{setBusy(false)}}
 return <main className="creative-engine-page"><header><a href="/app">← MODO</a><div><small>CREATE</small><h1>Criar com MODO</h1><p>Transforme uma intenção em imagem ou vídeo. A MODO organiza o briefing e mantém a aprovação com você.</p></div></header>
 <section className="creative-engine-grid"><form onSubmit={submit} className="creative-engine-card"><label>Marca<select value={brandId} onChange={e=>setBrandId(e.target.value)}>{brands.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><div className="creative-kind"><button type="button" className={kind==="image"?"active":""} onClick={()=>setKind("image")}>Imagem</button><button type="button" className={kind==="video"?"active":""} onClick={()=>setKind("video")}>Vídeo</button></div><label>Objetivo<input value={objective} onChange={e=>setObjective(e.target.value)}/></label><label>O que você quer criar?<textarea rows={7} value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Ex.: apresente nosso serviço para pessoas que cuidam dos pais, com linguagem humana e visual premium." required/></label><button className="creative-generate" disabled={busy||!brandId||!configured}>{busy?"Criando...":configured?"Criar com MODO":"Motor criativo aguardando configuração"}</button>{error&&<p className="creative-error">{error}</p>}<small>Nada é publicado automaticamente. O resultado entra na biblioteca para revisão e aprovação.</small></form>
 <section className="creative-engine-card"><div className="creative-library-head"><div><small>BIBLIOTECA CRIATIVA</small><h2>Criações da marca</h2></div><span>{items.length}</span></div>{!items.length?<p className="creative-empty">Suas imagens e vídeos aparecerão aqui.</p>:<div className="creative-assets">{items.map(item=><article key={item.id}><div className="creative-preview">{item.assets[0]?.url?(item.kind==="video"?<video controls src={item.assets[0].url}/>:<img src={item.assets[0].url} alt="Criação MODO"/>):<span>{item.status==="failed"?"Falhou":item.status==="ready"?"Pronto":"Gerando..."}</span>}</div><div><strong>{item.objective}</strong><small>{item.kind==="video"?"Vídeo":"Imagem"} · {item.status}</small></div></article>)}</div>}</section></section></main>
}
