import { useEffect, useState, type FormEvent } from "react";
import { createCreativeVariation, generateCreative, getCreativeEngineHealth, getCreativeGeneration, getDashboard, listCreativeLibrary, setCreativeApproval, type CreativeGeneration, previewCreativeVideoRoute, type VideoRoutePreview, getCreativeCostSummary, type CreativeCostSummary } from "./api";

export default function CreativeEngineWorkspace(){
 const [brandId,setBrandId]=useState("");const [brands,setBrands]=useState<Array<{id:string;name:string}>>([]);
 const [kind,setKind]=useState<"image"|"video">("image");const [objective,setObjective]=useState("Gerar demanda");const [prompt,setPrompt]=useState("");const [channel,setChannel]=useState("social");const [format,setFormat]=useState("vertical");
 const [costs,setCosts]=useState<CreativeCostSummary|null>(null);const [paidConfirmed,setPaidConfirmed]=useState(false);const [videoRoute,setVideoRoute]=useState<VideoRoutePreview|null>(null);const [items,setItems]=useState<CreativeGeneration[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [configured,setConfigured]=useState(false);
 useEffect(()=>{void (async()=>{try{const [d,h]=await Promise.all([getDashboard(),getCreativeEngineHealth()]);setBrands(d.brands.map(b=>({id:b.id,name:b.name})));const id=d.brands[0]?.id||"";setBrandId(id);setConfigured(h.providers.some(p=>p.configured));if(id)setItems((await listCreativeLibrary(id)).items)}catch(e){setError(e instanceof Error?e.message:"Não foi possível abrir o Creative Engine.")}})()},[]);
 useEffect(()=>{if(kind!=="video"){setVideoRoute(null);setPaidConfirmed(false);return;}const t=window.setTimeout(()=>{void previewCreativeVideoRoute({objective,channel,format}).then(setVideoRoute).catch(()=>setVideoRoute(null))},350);return()=>window.clearTimeout(t)},[kind,objective,channel,format]);
 useEffect(()=>{if(brandId){void listCreativeLibrary(brandId).then(x=>setItems(x.items)).catch(()=>undefined);void getCreativeCostSummary(brandId).then(setCosts).catch(()=>setCosts(null))}},[brandId]);
 useEffect(()=>{const pending=items.filter(x=>x.status==="queued"||x.status==="processing");if(!pending.length)return;const timer=window.setInterval(()=>{void Promise.all(pending.map(x=>getCreativeGeneration(x.id).catch(()=>x))).then(updated=>setItems(current=>current.map(item=>updated.find(x=>x.id===item.id)||item)))},2500);return()=>window.clearInterval(timer)},[items]);
 async function submit(e:FormEvent){e.preventDefault();setError("");setBusy(true);try{const created=await generateCreative({brandId,kind,objective,prompt,channel,format:kind==="image"?"social":format,provider:kind==="video"?"higgsfield":undefined,confirmPaidGeneration:kind==="video"?paidConfirmed:undefined});setItems(x=>[created,...x]);setPrompt("")}catch(e){setError(e instanceof Error?e.message:"Não foi possível gerar.")}finally{setBusy(false)}}
 return <main className="creative-engine-page"><header><a href="/app">← MODO</a><div><small>CREATE</small><h1>Criar com MODO</h1><p>Transforme uma intenção em imagem ou vídeo. A MODO organiza o briefing e mantém a aprovação com você.</p></div></header>
 {costs&&<section className="creative-cost-summary"><strong>Uso criativo</strong><span>{costs.generations} gerações</span><span>Custo registrado: US$ {costs.actualCostUsd.toFixed(2)}</span></section>}<section className="creative-engine-grid"><form onSubmit={submit} className="creative-engine-card"><label>Marca<select value={brandId} onChange={e=>setBrandId(e.target.value)}>{brands.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><div className="creative-kind"><button type="button" className={kind==="image"?"active":""} onClick={()=>setKind("image")}>Imagem</button><button type="button" className={kind==="video"?"active":""} onClick={()=>setKind("video")}>Vídeo</button></div>{kind==="video"&&videoRoute&&<p className="creative-route-note">MODO selecionou: <strong>{videoRoute.selectedUseCase.replaceAll("_"," ")}</strong>{videoRoute.fallback?" · usando fallback disponível":""}{videoRoute.maxDurationSeconds?` · até ${videoRoute.maxDurationSeconds}s`:""}</p>}{kind==="video"&&<label className="creative-paid-confirm"><input type="checkbox" checked={paidConfirmed} onChange={e=>setPaidConfirmed(e.target.checked)}/> Confirmo que esta geração de vídeo usa créditos pagos da Higgsfield.</label>}<label>Objetivo<input value={objective} onChange={e=>setObjective(e.target.value)}/></label>{kind==="video"&&<div className="creative-video-options"><label>Canal<select value={channel} onChange={e=>setChannel(e.target.value)}><option value="social">Social</option><option value="instagram">Instagram</option><option value="facebook">Facebook</option><option value="google_ads">Google Ads</option></select></label><label>Formato<select value={format} onChange={e=>setFormat(e.target.value)}><option value="vertical">Vertical 9:16</option><option value="landscape">Horizontal 16:9</option></select></label></div>}<label>O que você quer criar?<textarea rows={7} value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Ex.: apresente nosso serviço para pessoas que cuidam dos pais, com linguagem humana e visual premium." required/></label><button className="creative-generate" disabled={busy||!brandId||(kind==="video"&&(!configured||!paidConfirmed))}>{busy?"Criando...":configured?"Criar com MODO":"Motor criativo aguardando configuração"}</button>{error&&<p className="creative-error">{error}</p>}<small>Nada é publicado automaticamente. O resultado entra na biblioteca para revisão e aprovação.</small></form>
 <section className="creative-engine-card"><div className="creative-library-head"><div><small>BIBLIOTECA CRIATIVA</small><h2>Criações da marca</h2></div><span>{items.length}</span></div>{!items.length?<p className="creative-empty">Suas imagens e vídeos aparecerão aqui.</p>:<div className="creative-assets">{items.map(item=><article key={item.id}><div className="creative-preview">{item.assets[0]?.url?(item.kind==="video"?<video controls src={item.assets[0].url}/>:<img src={item.assets[0].url} alt="Criação MODO"/>):<span>{item.status==="failed"?"Falhou":item.status==="ready"?"Pronto":"Gerando..."}</span>}</div><div><strong>{item.objective}</strong><small>{item.kind==="video"?"Vídeo":"Imagem"} · {item.status}</small></div>{item.status==="ready"&&<div className="creative-approval"><button disabled={item.approvalStatus==="approved"} onClick={()=>void setCreativeApproval(item.id,"approved").then(next=>setItems(xs=>xs.map(x=>x.id===next.id?next:x)))}>{item.approvalStatus==="approved"?"✓ Aprovado":"Aprovar"}</button><button disabled={item.approvalStatus==="rejected"} onClick={()=>void setCreativeApproval(item.id,"rejected").then(()=>createCreativeVariation(item.id,undefined,item.kind==="video"?paidConfirmed:undefined)).then(next=>setItems(xs=>[next,...xs]))}>Refazer</button><button disabled={item.kind==="video"&&!paidConfirmed} onClick={()=>void createCreativeVariation(item.id,"Explore outra direção visual mantendo a mesma proposta.",item.kind==="video"?paidConfirmed:undefined).then(next=>setItems(xs=>[next,...xs]))}>Variação</button></div>}</article>)}</div>}</section></section></main>
}
