import { useMemo, useState } from "react";

type Objective="whatsapp"|"leads"|"sales"|"app"|"appointments";
const money=(n:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(n||0);
export default function DemandWorkspace(){
 const [business,setBusiness]=useState("");const [offer,setOffer]=useState("");const [objective,setObjective]=useState<Objective>("whatsapp");const [location,setLocation]=useState("Brasil");const [budget,setBudget]=useState(1500);const [ticket,setTicket]=useState(500);const [cpc,setCpc]=useState(3.5);const [landingRate,setLandingRate]=useState(7);const [closeRate,setCloseRate]=useState(20);const [built,setBuilt]=useState(false);
 const model=useMemo(()=>{const daily=budget/30;const clicks=budget/Math.max(.01,cpc);const leads=clicks*(landingRate/100);const customers=leads*(closeRate/100);const revenue=customers*ticket;return{daily,clicks,leads,customers,revenue,cpl:leads?budget/leads:0,cac:customers?budget/customers:0,roas:budget?revenue/budget:0}},[budget,ticket,cpc,landingRate,closeRate]);
 const objectiveLabel={whatsapp:"Conversas no WhatsApp",leads:"Leads",sales:"Vendas",app:"Instalações / ativação do app",appointments:"Agendamentos"}[objective];
 const build=()=>setBuilt(true);
 return <main className="demand-shell"><header className="demand-top"><a href="/app">← MODO</a><div><span>MODO GROWTH</span><h1>Demand Engine</h1><p>Da estratégia à aquisição mensurável. A MODO ajuda você a montar, publicar e melhorar seu funil.</p></div><a href="/app">Voltar ao painel</a></header>
 <section className="demand-hero"><div><div className="demand-kicker">COMECE DO ZERO</div><h2>Quero conseguir mais clientes.</h2><p>Você explica o negócio e o objetivo. A MODO organiza canal, público, orçamento, landing, campanha, tracking e métricas.</p></div><div className="demand-flow">NEGÓCIO <i>→</i> OFERTA <i>→</i> DEMANDA <i>→</i> LANDING <i>→</i> CONVERSÃO <i>→</i> LEARNING</div></section>
 <section className="demand-grid"><div className="demand-card"><div className="demand-kicker">01 · OBJETIVO</div><h2>O que precisamos vender?</h2><label>Negócio<input placeholder="Ex.: clínica de acupuntura" value={business} onChange={e=>setBusiness(e.target.value)}/></label><label>Oferta<input placeholder="Ex.: primeira consulta" value={offer} onChange={e=>setOffer(e.target.value)}/></label><label>Objetivo<select value={objective} onChange={e=>setObjective(e.target.value as Objective)}><option value="whatsapp">WhatsApp</option><option value="leads">Leads</option><option value="appointments">Agendamentos</option><option value="sales">Vendas</option><option value="app">App</option></select></label><label>Região<input value={location} onChange={e=>setLocation(e.target.value)}/></label><div className="demand-two"><label>Orçamento mensal (R$)<input type="number" min="0" value={budget} onChange={e=>setBudget(Number(e.target.value))}/></label><label>Ticket médio (R$)<input type="number" min="0" value={ticket} onChange={e=>setTicket(Number(e.target.value))}/></label></div><button onClick={build}>Montar plano de aquisição →</button></div>
 <div className="demand-card demand-model"><div className="demand-kicker">02 · CENÁRIO</div><h2>Antes de investir, faça as contas.</h2><p className="demand-note">Estimativa, não promessa de resultado. Ajuste as hipóteses; depois a MODO substitui estimativas pelos dados reais.</p><div className="demand-two"><label>CPC hipótese (R$)<input type="number" step="0.1" min="0.1" value={cpc} onChange={e=>setCpc(Number(e.target.value))}/></label><label>Conversão landing (%)<input type="number" step="0.1" min="0" max="100" value={landingRate} onChange={e=>setLandingRate(Number(e.target.value))}/></label></div><label>Lead → cliente (%)<input type="number" step="0.1" min="0" max="100" value={closeRate} onChange={e=>setCloseRate(Number(e.target.value))}/></label><div className="demand-metrics"><div><small>POR DIA</small><strong>{money(model.daily)}</strong></div><div><small>CLIQUES</small><strong>{Math.round(model.clicks)}</strong></div><div><small>LEADS</small><strong>{model.leads.toFixed(1)}</strong></div><div><small>CLIENTES</small><strong>{model.customers.toFixed(1)}</strong></div><div><small>CPL</small><strong>{money(model.cpl)}</strong></div><div><small>CAC</small><strong>{money(model.cac)}</strong></div><div><small>RECEITA HIP.</small><strong>{money(model.revenue)}</strong></div><div><small>ROAS HIP.</small><strong>{model.roas.toFixed(2)}x</strong></div></div></div></section>
 {built&&<><section className="demand-card demand-plan"><div className="demand-kicker">03 · PLANO MODO</div><div className="demand-plan-head"><div><h2>{business||"Seu negócio"}: plano inicial de aquisição</h2><p>Objetivo principal: <b>{objectiveLabel}</b> · {location} · {money(budget)}/mês</p></div><span>PLANO V1</span></div><div className="demand-steps">{[["1","Diagnóstico e políticas","Verificar elegibilidade do produto, mercado, claims, destino e requisitos do canal antes de anunciar."],["2","Intenção e público","Mapear demanda ativa, palavras-chave, negativas, geografia, audiência e hipótese de mensagem."],["3","Oferta e criativos",`Transformar ${offer||"a oferta"} em anúncios e variações de mensagem com CTA único.`],["4","Landing Builder","Criar página específica da campanha: hero, prova, benefícios, CTA, FAQ, compliance e mobile."],["5","Tracking","Preparar UTMs e eventos: visita → CTA → lead → qualificado → venda/ativação."],["6","Google Ads Copilot","Orientar passo a passo a criação da campanha, orçamento, localização, keywords, anúncios e conversões."],["7","Funil","Trazer investimento, cliques, leads, clientes, CPL, CAC, receita e ROAS para uma visão única."],["8","Learning","Detectar vazamentos, propor testes e registrar o que funcionou para a próxima campanha."]].map(([n,t,d])=><article key={n}><b>{n}</b><div><h3>{t}</h3><p>{d}</p></div><em>→</em></article>)}</div></section>
 <section className="demand-grid"><div className="demand-card"><div className="demand-kicker">04 · LANDING BUILDER</div><h2>Uma página para converter, não uma homepage.</h2><div className="demand-checks"><span>✓ Proposta clara</span><span>✓ CTA principal</span><span>✓ WhatsApp / cadastro / app</span><span>✓ Prova e objeções</span><span>✓ FAQ</span><span>✓ Mobile</span><span>✓ UTMs + eventos</span><span>✓ Rodapé e compliance</span></div><button disabled>Gerar landing · próxima entrega</button></div><div className="demand-card"><div className="demand-kicker">05 · GOOGLE ADS COPILOT</div><h2>Sem precisar saber Google Ads.</h2><div className="demand-guide"><strong>Passo 1 de 11</strong><p>A MODO vai verificar primeiro se o negócio e o destino podem ser anunciados e qual tipo de campanha faz sentido.</p><button disabled>Começar configuração guiada · próxima entrega</button></div></div></section>
 <section className="demand-card demand-funnel"><div><div className="demand-kicker">06 · FUNIL</div><h2>O clique não é o resultado.</h2><p>A otimização deve chegar até a conversão de negócio.</p></div><div className="demand-funnel-line"><span>INVESTIMENTO</span><i>→</i><span>VISITAS</span><i>→</i><span>{objective==="app"?"INSTALAÇÕES":"LEADS"}</span><i>→</i><span>QUALIFICADOS</span><i>→</i><span>CLIENTES</span><i>→</i><span>RECEITA</span></div></section></>}
 </main>;
}