import { useMemo, useState } from "react";

type Lead={id:string;name:string;role?:string;company:string;fitScore:number;reason?:string;signal?:string;email?:string;linkedinUrl?:string;status:string;source?:string};
type Approach={subject:string;message:string;channel:string};
const API_URL=(import.meta.env.VITE_API_URL||"http://localhost:4000").replace(/\/$/,"");
async function api<T>(path:string,init?:RequestInit):Promise<T>{const token=window.localStorage.getItem("modo.sessionToken")||"";const response=await fetch(`${API_URL}${path}`,{...init,headers:{"content-type":"application/json",...(token?{authorization:`Bearer ${token}`}:{ }),...init?.headers}});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.message||"Não foi possível concluir a solicitação.");return payload as T}

export default function ProspectorWorkspace(){
 const [segment,setSegment]=useState("Contabilidade e serviços B2B");const [roles,setRoles]=useState("Sócio, CEO, Diretor, Head de Growth");const [location,setLocation]=useState("Brasil");const [size,setSize]=useState("10–100 funcionários");const [offer,setOffer]=useState("SmartBots");const [running,setRunning]=useState(false);const [ready,setReady]=useState(false);const [leads,setLeads]=useState<Lead[]>([]);const [error,setError]=useState("");const [provider,setProvider]=useState("");const [approach,setApproach]=useState<{lead:Lead;draft:Approach}|null>(null);const [approachLoading,setApproachLoading]=useState("");
 const summary=useMemo(()=>`${segment} · ${roles} · ${location} · ${size}`,[segment,roles,location,size]);
 async function prospect(){setRunning(true);setReady(false);setError("");setLeads([]);try{const campaign=await api<{id:string}>("/api/v1/prospector/campaigns",{method:"POST",body:JSON.stringify({name:`Prospecção ${segment}`,segment,roles:roles.split(",").map(x=>x.trim()).filter(Boolean),location,companySize:size,offer})});const result=await api<{provider:string;leads:Lead[]}>(`/api/v1/prospector/campaigns/${campaign.id}/discover`,{method:"POST",body:JSON.stringify({limit:20})});setProvider(result.provider);setLeads(result.leads);setReady(true)}catch(caught){setError(caught instanceof Error?caught.message:"Falha ao prospectar.")}finally{setRunning(false)}}
 async function prepare(lead:Lead){setApproachLoading(lead.id);setError("");try{const draft=await api<Approach>(`/api/v1/prospector/leads/${lead.id}/approach`,{method:"POST",body:JSON.stringify({channel:lead.email?"email":"linkedin"})});setApproach({lead,draft})}catch(caught){setError(caught instanceof Error?caught.message:"Falha ao preparar abordagem.")}finally{setApproachLoading("")}}
 return <main className="prospector-shell"><header className="prospector-top"><a href="/app">← MODO</a><div><span>MODO SALES</span><h1>Prospector</h1><p>Do cliente ideal à abordagem certa, com inteligência antes do contato.</p></div><a className="prospector-back" href="/app">Voltar ao painel</a></header>
 <section className="prospector-grid"><div className="prospector-card prospector-icp"><div className="prospector-kicker">01 · ICP</div><h2>Quem você quer encontrar?</h2><p>Descreva o mercado. A MODO transforma sua intenção em critérios de prospecção.</p><label>Segmento<input value={segment} onChange={e=>setSegment(e.target.value)}/></label><label>Cargos decisores<input value={roles} onChange={e=>setRoles(e.target.value)}/></label><div className="prospector-row"><label>Localização<input value={location} onChange={e=>setLocation(e.target.value)}/></label><label>Tamanho<input value={size} onChange={e=>setSize(e.target.value)}/></label></div><label>O que vamos oferecer?<input value={offer} onChange={e=>setOffer(e.target.value)}/></label><button onClick={prospect} disabled={running}>{running?"Buscando empresas e decisores...":"Encontrar oportunidades →"}</button><small>{summary}</small>{error&&<div className="prospector-error">{error}</div>}</div>
 <div className="prospector-card prospector-engine"><div className="prospector-kicker">02 · MOTOR</div><h2>A MODO faz o trabalho pesado.</h2>{["Descobrir empresas compatíveis","Identificar decisores","Enriquecer contexto público","Detectar sinais de oportunidade","Calcular Fit Score","Preparar abordagem individual","Enviar para aprovação humana"].map((x,i)=><div className="prospector-step" key={x}><b>{String(i+1).padStart(2,"0")}</b><span>{x}</span><em>{ready?"✓":"→"}</em></div>)}{provider&&<small>Provider ativo: <b>{provider}</b></small>}</div></section>
 <section className="prospector-results"><div className="prospector-results-head"><div><div className="prospector-kicker">03 · OPORTUNIDADES</div><h2>{ready?`${leads.length} leads priorizados`:"Defina o ICP e inicie a busca"}</h2></div><span className="prospector-badge">Quality Gate + aprovação humana</span></div>{ready&&leads.length===0?<p className="prospector-empty">Nenhuma oportunidade nova encontrada para este ICP. Ajuste os critérios ou o provider.</p>:<div className="prospector-leads">{leads.map(l=><article className="prospector-lead" key={l.id}><div className="prospector-score"><strong>{l.fitScore}</strong><span>FIT</span></div><div><h3>{l.name}</h3><p className="prospector-role">{l.role||"Decisor"} · {l.company}</p><p><b>Por que agora:</b> {l.reason||"Aderência aos critérios definidos."}</p>{l.signal&&<p><b>Sinal:</b> {l.signal}</p>}<div className="prospector-actions"><span>{l.email?"E-mail":l.linkedinUrl?"LinkedIn":l.source||"Lead"}</span><button onClick={()=>prepare(l)} disabled={approachLoading===l.id}>{approachLoading===l.id?"Preparando...":"Preparar abordagem"}</button></div></div></article>)}</div>}</section>
 {approach&&<section className="prospector-results prospector-approach"><div className="prospector-results-head"><div><div className="prospector-kicker">04 · ABORDAGEM</div><h2>{approach.lead.name} · {approach.lead.company}</h2></div><button className="prospector-close" onClick={()=>setApproach(null)}>Fechar</button></div><label>Assunto<input value={approach.draft.subject} onChange={e=>setApproach({...approach,draft:{...approach.draft,subject:e.target.value}})}/></label><label>Mensagem<textarea rows={7} value={approach.draft.message} onChange={e=>setApproach({...approach,draft:{...approach.draft,message:e.target.value}})}/></label><div className="prospector-approval-note">Rascunho criado pela MODO. Revise e aprove antes de qualquer envio.</div></section>}
 <section className="prospector-loop"><span>ATTRACT</span><i>→</i><span>IDENTIFY</span><i>→</i><span>PROSPECT</span><i>→</i><span>CONVERT</span><i>→</i><span>LEARN</span><i>↻</i></section></main>
}