import { useMemo, useState } from "react";

type Lead={name:string;role:string;company:string;score:number;reason:string;signal:string;channel:string};
const demo:Lead[]=[
{name:"Marina Costa",role:"Sócia-diretora",company:"Atlas Contabilidade",score:94,reason:"Perfil decisor e operação B2B com forte aderência ao ICP.",signal:"Atendimento comercial via WhatsApp e expansão de serviços.",channel:"E-mail + WhatsApp"},
{name:"Rafael Nunes",role:"CEO",company:"Nexo Consultoria",score:89,reason:"Empresa de serviços com venda consultiva e equipe enxuta.",signal:"Crescimento recente e necessidade provável de escala comercial.",channel:"LinkedIn + E-mail"},
{name:"Camila Ribeiro",role:"Head de Growth",company:"Vértice B2B",score:86,reason:"Responsável direta por aquisição e geração de demanda.",signal:"Conteúdo frequente, mas baixa evidência de outbound estruturado.",channel:"LinkedIn"},
];
export default function ProspectorWorkspace(){
 const [segment,setSegment]=useState("Contabilidade e serviços B2B"); const [roles,setRoles]=useState("Sócio, CEO, Diretor, Head de Growth"); const [location,setLocation]=useState("Brasil"); const [size,setSize]=useState("10–100 funcionários"); const [offer,setOffer]=useState("SmartBots"); const [running,setRunning]=useState(false); const [ready,setReady]=useState(false);
 const summary=useMemo(()=>`${segment} · ${roles} · ${location} · ${size}`,[segment,roles,location,size]);
 function prospect(){setRunning(true);setReady(false);window.setTimeout(()=>{setRunning(false);setReady(true)},850)}
 return <main className="prospector-shell"><header className="prospector-top"><a href="/app">← MODO</a><div><span>MODO SALES</span><h1>Prospector</h1><p>Do cliente ideal à abordagem certa, com inteligência antes do contato.</p></div><a className="prospector-back" href="/app">Voltar ao painel</a></header>
 <section className="prospector-grid"><div className="prospector-card prospector-icp"><div className="prospector-kicker">01 · ICP</div><h2>Quem você quer encontrar?</h2><p>Descreva o mercado. A MODO transforma sua intenção em critérios de prospecção.</p><label>Segmento<input value={segment} onChange={e=>setSegment(e.target.value)}/></label><label>Cargos decisores<input value={roles} onChange={e=>setRoles(e.target.value)}/></label><div className="prospector-row"><label>Localização<input value={location} onChange={e=>setLocation(e.target.value)}/></label><label>Tamanho<input value={size} onChange={e=>setSize(e.target.value)}/></label></div><label>O que vamos oferecer?<input value={offer} onChange={e=>setOffer(e.target.value)}/></label><button onClick={prospect} disabled={running}>{running?"Analisando ICP...":"Encontrar oportunidades →"}</button><small>{summary}</small></div>
 <div className="prospector-card prospector-engine"><div className="prospector-kicker">02 · MOTOR</div><h2>A MODO faz o trabalho pesado.</h2>{["Descobrir empresas compatíveis","Identificar decisores","Enriquecer contexto público","Detectar sinais de oportunidade","Calcular Fit Score","Preparar abordagem individual","Enviar para aprovação humana"].map((x,i)=><div className="prospector-step" key={x}><b>{String(i+1).padStart(2,"0")}</b><span>{x}</span><em>{ready?"✓":"→"}</em></div>)}</div></section>
 <section className="prospector-results"><div className="prospector-results-head"><div><div className="prospector-kicker">03 · OPORTUNIDADES</div><h2>{ready?"Leads priorizados":"Prévia do que você receberá"}</h2></div><span className="prospector-badge">Quality Gate + aprovação humana</span></div><div className="prospector-leads">{demo.map(l=><article className="prospector-lead" key={l.company}><div className="prospector-score"><strong>{l.score}</strong><span>FIT</span></div><div><h3>{l.name}</h3><p className="prospector-role">{l.role} · {l.company}</p><p><b>Por que agora:</b> {l.reason}</p><p><b>Sinal:</b> {l.signal}</p><div className="prospector-actions"><span>{l.channel}</span><button>Preparar abordagem</button></div></div></article>)}</div></section>
 <section className="prospector-loop"><span>ATTRACT</span><i>→</i><span>IDENTIFY</span><i>→</i><span>PROSPECT</span><i>→</i><span>CONVERT</span><i>→</i><span>LEARN</span><i>↻</i></section></main>
}