import AdminWorkspace from "./AdminWorkspace";
import BillingWorkspace from "./BillingWorkspace";
import CampaignWorkspace from "./CampaignWorkspace";
import ContentWorkspace from "./ContentWorkspace";
import DirectorWorkspace from "./DirectorWorkspace";
import HumanOperationsAdminWorkspace from "./HumanOperationsAdminWorkspace";
import ImpactLanding from "./ImpactLanding";
import IntelligenceWorkspace from "./IntelligenceWorkspace";
import IntegrationsWorkspace from "./IntegrationsWorkspace";
import InvitationWorkspace from "./InvitationWorkspace";
import LinkedInWorkspace from "./LinkedInWorkspace";
import OnboardingWorkspace from "./OnboardingWorkspace";
import Portal from "./Portal";
import PortalWelcomeGuide from "./PortalWelcomeGuide";
import SignalWorkspace from "./SignalWorkspace";
import SmartBotsAdminWorkspace from "./SmartBotsAdminWorkspace";
import SmartBotsOnboarding from "./SmartBotsOnboarding";
import SmartBotsPage from "./SmartBotsPage";
import SpecialistApplicationPage from "./SpecialistApplicationPage";
import SpecialistSupportWorkspace from "./SpecialistSupportWorkspace";
import StrategyWorkspace from "./StrategyWorkspace";
import StudioWorkspace from "./StudioWorkspace";
import WeekWorkspace from "./WeekWorkspace";

export default function Root() {
  const path = window.location.pathname;
  if (path === "/smartbots.html" || path === "/smartbots") return <SmartBotsPage />;
  if (path === "/onboarding-smartbots.html" || path === "/app/smartbots") return <SmartBotsOnboarding />;
  if (path === "/rede-modo/convite") return <SpecialistApplicationPage />;
  if (path === "/especialistas" || path === "/rede-modo") { window.location.replace("/"); return null }
  if (path === "/admin/smartbots") return <SmartBotsAdminWorkspace />;
  if (path === "/admin/rede") return <HumanOperationsAdminWorkspace />;
  if (path.startsWith("/admin")) return <><AdminWorkspace /><div style={{ position: "fixed", right: 22, bottom: 22, zIndex: 1000, display: "flex", gap: 8 }}><a href="/admin/rede" style={{ background: "#1F5EFF", color: "#fff", borderRadius: 999, padding: "12px 17px", fontSize: 11, fontWeight: 900, boxShadow: "0 15px 40px rgba(13,27,62,.2)", textDecoration: "none" }}>Time Modo</a><a href="/admin/smartbots" style={{ background: "#2ED19A", color: "#0D1B3E", borderRadius: 999, padding: "12px 17px", fontSize: 11, fontWeight: 900, boxShadow: "0 15px 40px rgba(13,27,62,.2)", textDecoration: "none" }}>SmartBots</a></div></>;
  if (path.startsWith("/convite/")) return <InvitationWorkspace />;
  if (path.startsWith("/app/onboarding")) return <OnboardingWorkspace />;
  if (path.startsWith("/app/studio/")) return <StudioWorkspace />;
  if (path.startsWith("/app/base")) return <StrategyWorkspace />;
  if (path.startsWith("/app/especialista")) return <SpecialistSupportWorkspace />;
  if (path.startsWith("/app/week")) return <WeekWorkspace />;
  if (path.startsWith("/app/planos")) return <BillingWorkspace />;
  if (path.startsWith("/app/director")) return <DirectorWorkspace />;
  if (path.startsWith("/app/campanhas")) return <CampaignWorkspace />;
  if (path.startsWith("/app/linkedin")) return <LinkedInWorkspace />;
  if (path.startsWith("/app/inteligencia")) return <IntelligenceWorkspace />;
  if (path.startsWith("/app/signal")) return <SignalWorkspace />;
  if (path.startsWith("/app/settings/integrations")) return <IntegrationsWorkspace />;
  if (path.startsWith("/app/content")) return <ContentWorkspace />;
  if (path.startsWith("/app")) return <><Portal /><PortalWelcomeGuide /><div className="portal-floating-actions"><a className="portal-plan-entry" href="/app/onboarding">Primeiros passos</a><a className="portal-plan-entry" href="/app/base">Base estratégica</a><a className="portal-plan-entry" href="/app/week">Minha semana</a><a className="portal-plan-entry" href="/app/director">Diretor</a><a className="portal-plan-entry" href="/app/campanhas">Campanhas</a><a className="portal-plan-entry" href="/app/linkedin">LinkedIn</a><a className="portal-plan-entry" href="/app/inteligencia">Inteligência</a><a className="portal-plan-entry" href="/onboarding-smartbots.html">SmartBots</a><a className="portal-plan-entry" href="/app/signal">Signal</a><a className="portal-plan-entry" href="/app/settings/integrations">Integrações</a><a className="portal-workspace-entry" href="/app/content">Quick Start e criar ↗</a></div></>;
  return <ImpactLanding />;
}
