import{createCipheriv,createDecipheriv,createHash,randomBytes,randomUUID}from"node:crypto";import pg from"pg";

export class GoogleAdsError extends Error{constructor(public code:string,public status:number,message:string,public detail?:unknown){super(message)}}
type Options={databaseUrl?:string;databaseSsl?:boolean;clientId?:string;clientSecret?:string;redirectUri?:string;encryptionSecret?:string;apiVersion?:string;developerToken?:string};
type OAuthState={id:string;ownerId:string;connectionId:string;stateHash:string;expiresAt:string;usedAt?:string|null};

export class GoogleAdsService{
 private pool?:pg.Pool;private states:OAuthState[]=[];public readonly apiVersion:string;private options:Options;
 constructor(options:Options={}){this.options={databaseUrl:options.databaseUrl,databaseSsl:options.databaseSsl,clientId:options.clientId||process.env.GOOGLE_ADS_CLIENT_ID,clientSecret:options.clientSecret||process.env.GOOGLE_ADS_CLIENT_SECRET,redirectUri:options.redirectUri||process.env.GOOGLE_ADS_REDIRECT_URI,encryptionSecret:options.encryptionSecret||process.env.GOOGLE_ADS_TOKEN_ENCRYPTION_SECRET,apiVersion:options.apiVersion||process.env.GOOGLE_ADS_API_VERSION||"v25",developerToken:options.developerToken||process.env.GOOGLE_ADS_DEVELOPER_TOKEN};if(this.options.databaseUrl)this.pool=new pg.Pool({connectionString:this.options.databaseUrl,ssl:this.options.databaseSsl?{rejectUnauthorized:false}:undefined});this.apiVersion=this.options.apiVersion||"v25"}
 get configured(){return Boolean(this.options.clientId&&this.options.clientSecret&&this.options.redirectUri&&this.options.encryptionSecret)}
 async initialize(){if(!this.pool)return;await this.pool.query(`alter table media_connections add column if not exists credential_ciphertext text`);await this.pool.query(`create table if not exists media_oauth_states(id uuid primary key,owner_id text not null,connection_id uuid not null,state_hash text not null unique,provider text not null,expires_at timestamptz not null,used_at timestamptz,created_at timestamptz not null default now())`);await this.pool.query(`create index if not exists idx_media_oauth_state_expiry on media_oauth_states(provider,expires_at)`) }
 async close(){await this.pool?.end()}
 private owner(c:any){const id=c?.organization?.id||c?.organizationId||c?.user?.id||c?.id;if(!id)throw new GoogleAdsError("OWNER_REQUIRED",401,"Sessão inválida.");return String(id)}
 private key(){if(!this.options.encryptionSecret)throw new GoogleAdsError("GOOGLE_ADS_NOT_CONFIGURED",503,"Configure a criptografia OAuth do Google Ads.");return createHash("sha256").update(this.options.encryptionSecret).digest()}
 private encrypt(value:string){const iv=randomBytes(12),cipher=createCipheriv("aes-256-gcm",this.key(),iv),body=Buffer.concat([cipher.update(value,"utf8"),cipher.final()]),tag=cipher.getAuthTag();return`v1.${iv.toString("base64url")}.${tag.toString("base64url")}.${body.toString("base64url")}`}
 private decrypt(value:string){const [version,iv,tag,body]=String(value||"").split(".");if(version!=="v1"||!iv||!tag||!body)throw new GoogleAdsError("INVALID_OAUTH_CREDENTIAL",500,"Credencial OAuth inválida.");const decipher=createDecipheriv("aes-256-gcm",this.key(),Buffer.from(iv,"base64url"));decipher.setAuthTag(Buffer.from(tag,"base64url"));return Buffer.concat([decipher.update(Buffer.from(body,"base64url")),decipher.final()]).toString("utf8")}
 private hash(v:string){return createHash("sha256").update(v).digest("hex")}
 private normalizeCustomerId(v:unknown){return String(v||"").replace(/\D/g,"")}
 private async storeState(row:OAuthState){if(this.pool)await this.pool.query(`insert into media_oauth_states(id,owner_id,connection_id,state_hash,provider,expires_at) values($1,$2,$3,$4,'google_ads',$5)`,[row.id,row.ownerId,row.connectionId,row.stateHash,row.expiresAt]);else this.states.push(row)}
 async prepare(context:any,connectionId:string){if(!this.configured)return{ready:false,reason:"google_oauth_configuration_required",required:["GOOGLE_ADS_CLIENT_ID","GOOGLE_ADS_CLIENT_SECRET","GOOGLE_ADS_REDIRECT_URI","GOOGLE_ADS_TOKEN_ENCRYPTION_SECRET"]};const owner=this.owner(context);if(this.pool){const r=await this.pool.query(`select id from media_connections where id=$1 and owner_id=$2 and provider='google_ads'`,[connectionId,owner]);if(!r.rowCount)throw new GoogleAdsError("CONNECTION_NOT_FOUND",404,"Conexão Google Ads não encontrada.")}const state=randomBytes(32).toString("base64url"),expiresAt=new Date(Date.now()+10*60_000).toISOString();await this.storeState({id:randomUUID(),ownerId:owner,connectionId,stateHash:this.hash(state),expiresAt});const url=new URL("https://accounts.google.com/o/oauth2/v2/auth");url.searchParams.set("client_id",this.options.clientId!);url.searchParams.set("redirect_uri",this.options.redirectUri!);url.searchParams.set("response_type","code");url.searchParams.set("scope","https://www.googleapis.com/auth/adwords");url.searchParams.set("access_type","offline");url.searchParams.set("prompt","consent");url.searchParams.set("include_granted_scopes","true");url.searchParams.set("state",state);return{ready:true,authorizationUrl:url.toString(),expiresAt,scope:"https://www.googleapis.com/auth/adwords",offlineAccess:true}}
 private async consumeState(state:string){const hash=this.hash(state);let row:any;if(this.pool){const{rows}=await this.pool.query(`select id,owner_id as "ownerId",connection_id as "connectionId",expires_at as "expiresAt",used_at as "usedAt" from media_oauth_states where state_hash=$1 and provider='google_ads'`,[hash]);row=rows[0]}else row=this.states.find(x=>x.stateHash===hash);if(!row)throw new GoogleAdsError("INVALID_OAUTH_STATE",400,"Estado OAuth inválido.");if(row.usedAt)throw new GoogleAdsError("OAUTH_STATE_USED",409,"Esta autorização já foi concluída.");if(new Date(row.expiresAt).getTime()<Date.now())throw new GoogleAdsError("OAUTH_STATE_EXPIRED",400,"A autorização expirou. Inicie novamente.");if(this.pool)await this.pool.query(`update media_oauth_states set used_at=now() where id=$1`,[row.id]);else row.usedAt=new Date().toISOString();return row}
 private async exchangeCode(code:string){const body=new URLSearchParams({code,client_id:this.options.clientId!,client_secret:this.options.clientSecret!,redirect_uri:this.options.redirectUri!,grant_type:"authorization_code"});const r=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body,signal:AbortSignal.timeout(20_000)});const payload:any=await r.json().catch(()=>({}));if(!r.ok)throw new GoogleAdsError("OAUTH_EXCHANGE_FAILED",502,"O Google não concluiu a autorização.",payload);if(!payload.access_token)throw new GoogleAdsError("OAUTH_ACCESS_TOKEN_MISSING",502,"O Google não retornou access token.");if(!payload.refresh_token)throw new GoogleAdsError("OAUTH_REFRESH_TOKEN_MISSING",409,"O Google não retornou refresh token. Revogue o consentimento anterior e autorize novamente.");return payload}
 private headers(accessToken:string){const h:Record<string,string>={authorization:`Bearer ${accessToken}`,"content-type":"application/json"};if(this.options.developerToken)h["developer-token"]=this.options.developerToken;return h}
 private async accessibleCustomers(accessToken:string){const r=await fetch(`https://googleads.googleapis.com/${this.apiVersion}/customers:listAccessibleCustomers`,{headers:this.headers(accessToken),signal:AbortSignal.timeout(20_000)});const payload:any=await r.json().catch(()=>({}));if(!r.ok)throw new GoogleAdsError("GOOGLE_ADS_ACCOUNTS_FAILED",502,"Não foi possível consultar as contas Google Ads autorizadas.",payload);return(Array.isArray(payload.resourceNames)?payload.resourceNames:[]).map((x:string)=>this.normalizeCustomerId(x)).filter(Boolean)}
 async callback(state:string,code:string){if(!this.configured)throw new GoogleAdsError("GOOGLE_ADS_NOT_CONFIGURED",503,"OAuth Google Ads não configurado.");const s=await this.consumeState(state),token=await this.exchangeCode(code),customerIds=await this.accessibleCustomers(token.access_token);if(!customerIds.length)throw new GoogleAdsError("NO_GOOGLE_ADS_ACCOUNTS",409,"A conta Google autorizada não possui uma conta Google Ads acessível.");const metadata={authorizationSource:"google_oauth_callback",authorizedAt:new Date().toISOString(),accessibleCustomerIds:customerIds,apiVersion:this.apiVersion,accountSelectionRequired:true};if(this.pool)await this.pool.query(`update media_connections set status='oauth_authorized',scopes=$1::jsonb,metadata=$2::jsonb,credential_ciphertext=$3,updated_at=now() where id=$4 and owner_id=$5 and provider='google_ads'`,[JSON.stringify(["https://www.googleapis.com/auth/adwords"]),JSON.stringify(metadata),this.encrypt(token.refresh_token),s.connectionId,s.ownerId]);return{connectionId:s.connectionId,workspaceOwner:s.ownerId,status:"oauth_authorized",accessibleCustomerIds:customerIds,accountSelectionRequired:true}}
 async selectAccount(context:any,connectionId:string,input:any){const owner=this.owner(context),customerId=this.normalizeCustomerId(input?.customerId),accountName=String(input?.accountName||`Google Ads ${customerId}`).slice(0,160);if(!customerId)throw new GoogleAdsError("CUSTOMER_REQUIRED",400,"Selecione uma conta Google Ads.");if(!this.pool)throw new GoogleAdsError("PERSISTENCE_REQUIRED",503,"Conexão Google Ads requer persistência segura.");const{rows}=await this.pool.query(`select id,status,metadata,credential_ciphertext from media_connections where id=$1 and owner_id=$2 and provider='google_ads'`,[connectionId,owner]);const row=rows[0];if(!row?.credential_ciphertext||row.status!=="oauth_authorized")throw new GoogleAdsError("OAUTH_REQUIRED",409,"Conclua o OAuth oficial do Google Ads antes de escolher a conta.");const allowed=(Array.isArray(row.metadata?.accessibleCustomerIds)?row.metadata.accessibleCustomerIds:[]).map((x:any)=>this.normalizeCustomerId(x));if(!allowed.includes(customerId))throw new GoogleAdsError("CUSTOMER_NOT_AUTHORIZED",403,"Essa conta não foi retornada pelo OAuth Google Ads.");const metadata={...row.metadata,selectedCustomerId:customerId,accountSelectionRequired:false,connectedAt:new Date().toISOString()};const updated=await this.pool.query(`update media_connections set external_account_id=$1,account_name=$2,status='connected',metadata=$3::jsonb,updated_at=now() where id=$4 and owner_id=$5 returning id,provider,external_account_id as "externalAccountId",account_name as "accountName",status,scopes,metadata,created_at as "createdAt",updated_at as "updatedAt"`,[customerId,accountName,JSON.stringify(metadata),connectionId,owner]);return updated.rows[0]}
 private async refreshAccessToken(refreshToken:string){const body=new URLSearchParams({client_id:this.options.clientId!,client_secret:this.options.clientSecret!,refresh_token:refreshToken,grant_type:"refresh_token"});const r=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body,signal:AbortSignal.timeout(20_000)});const payload:any=await r.json().catch(()=>({}));if(!r.ok||!payload.access_token)throw new GoogleAdsError("TOKEN_REFRESH_FAILED",502,"Não foi possível renovar o acesso ao Google Ads.",payload);return payload.access_token as string}
 async metrics(context:any,days=30){const owner=this.owner(context);if(!this.pool)throw new GoogleAdsError("PERSISTENCE_REQUIRED",503,"Métricas Google Ads requerem persistência segura.");const{rows}=await this.pool.query(`select id,external_account_id as "customerId",account_name as "accountName",credential_ciphertext from media_connections where owner_id=$1 and provider='google_ads' and status='connected' order by updated_at desc limit 1`,[owner]);const row=rows[0];if(!row?.credential_ciphertext||!row.customerId)throw new GoogleAdsError("GOOGLE_ADS_NOT_CONNECTED",409,"Conecte uma conta Google Ads para consultar métricas reais.");const accessToken=await this.refreshAccessToken(this.decrypt(row.credential_ciphertext)),safeDays=Math.min(90,Math.max(1,Math.floor(days))),end=new Date(),start=new Date(Date.now()-(safeDays-1)*86400000),iso=(d:Date)=>d.toISOString().slice(0,10);const query=`SELECT metrics.impressions, metrics.clicks, metrics.cost_micros, metrics.conversions, metrics.conversions_value FROM campaign WHERE segments.date BETWEEN '${iso(start)}' AND '${iso(end)}'`;const r=await fetch(`https://googleads.googleapis.com/${this.apiVersion}/customers/${row.customerId}/googleAds:searchStream`,{method:"POST",headers:this.headers(accessToken),body:JSON.stringify({query}),signal:AbortSignal.timeout(30_000)});const payload:any=await r.json().catch(()=>({}));if(!r.ok)throw new GoogleAdsError("GOOGLE_ADS_METRICS_FAILED",502,"Não foi possível consultar as métricas da conta Google Ads.",payload);const batches=Array.isArray(payload)?payload:[payload],results=batches.flatMap((b:any)=>Array.isArray(b?.results)?b.results:[]);let impressions=0,clicks=0,costMicros=0,conversions=0,conversionValue=0;for(const item of results){const m=item?.metrics||{};impressions+=Number(m.impressions||0);clicks+=Number(m.clicks||0);costMicros+=Number(m.costMicros||m.cost_micros||0);conversions+=Number(m.conversions||0);conversionValue+=Number(m.conversionsValue||m.conversions_value||0)}const costMinor=Math.round(costMicros/10_000),conversionValueMinor=Math.round(conversionValue*100);return{source:"google_ads_api",actual:true,apiVersion:this.apiVersion,connectionId:row.id,customerId:row.customerId,accountName:row.accountName,period:{days:safeDays,start:iso(start),end:iso(end)},impressions,clicks,costMinor,conversions,conversionValueMinor,cpcMinor:clicks?Math.round(costMinor/clicks):null,costPerConversionMinor:conversions?Math.round(costMinor/conversions):null,roas:costMinor?Math.round((conversionValueMinor/costMinor)*100)/100:null}}
}
