import { randomUUID } from "node:crypto";
import pg from "pg";

export type ProspectorCampaignStatus="draft"|"ready"|"running"|"paused"|"completed";
export type ProspectorLeadStatus="new"|"qualified"|"approved"|"contacted"|"replied"|"meeting"|"won"|"lost";
export interface ProspectorIcpInput{name?:string;segment:string;roles:string[];location?:string;companySize?:string;offer?:string;notes?:string}
export interface ProspectorLeadInput{campaignId:string;name:string;role?:string;company:string;email?:string;linkedinUrl?:string;websiteUrl?:string;location?:string;fitScore?:number;reason?:string;signal?:string;source?:string;sourceRef?:string;metadata?:Record<string,unknown>}
export class ProspectorError extends Error{constructor(public code:string,public status:number,message:string){super(message)}}
export class ProspectorService{
 private pool?:pg.Pool;public readonly storage:"postgres"|"memory";private campaigns=new Map<string,any>();private leads=new Map<string,any>();
 constructor(private options:{databaseUrl?:string;databaseSsl?:boolean}){this.storage=options.databaseUrl?"postgres":"memory";if(options.databaseUrl)this.pool=new pg.Pool({connectionString:options.databaseUrl,ssl:options.databaseSsl?{rejectUnauthorized:false}:undefined})}
 async initialize(){if(!this.pool)return;await this.pool.query(`create table if not exists prospector_campaigns (id uuid primary key, owner_id text not null, name text not null, status text not null default 'draft', segment text not null, roles jsonb not null default '[]'::jsonb, location text, company_size text, offer text, notes text, provider text not null default 'manual', created_at timestamptz not null default now(), updated_at timestamptz not null default now())`);await this.pool.query(`create table if not exists prospector_leads (id uuid primary key, owner_id text not null, campaign_id uuid not null references prospector_campaigns(id) on delete cascade, name text not null, role text, company text not null, email text, linkedin_url text, website_url text, location text, fit_score integer not null default 0, reason text, signal text, status text not null default 'new', source text not null default 'manual', source_ref text, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now())`);await this.pool.query(`create index if not exists idx_prospector_campaigns_owner on prospector_campaigns(owner_id,created_at desc)`);await this.pool.query(`create index if not exists idx_prospector_leads_campaign on prospector_leads(campaign_id,fit_score desc,created_at desc)`)}
 async close(){await this.pool?.end()}
 private ownerId(context:any){return String(context?.organization?.id||context?.organizationId||context?.user?.id||context?.id||"unknown")}
 async createCampaign(context:any,input:ProspectorIcpInput){if(!input.segment?.trim())throw new ProspectorError("INVALID_ICP",400,"Informe o segmento do ICP.");const now=new Date().toISOString(),id=randomUUID(),owner=this.ownerId(context),name=input.name?.trim()||`ICP ${input.segment.trim()}`;const row={id,ownerId:owner,name,status:"draft",segment:input.segment.trim(),roles:(input.roles||[]).filter(Boolean),location:input.location||null,companySize:input.companySize||null,offer:input.offer||null,notes:input.notes||null,provider:"manual",createdAt:now,updatedAt:now};if(this.pool)await this.pool.query(`insert into prospector_campaigns(id,owner_id,name,status,segment,roles,location,company_size,offer,notes,provider) values($1,$2,$3,$4,$5,$6::jsonb,$7,$8,$9,$10,$11)`,[id,owner,name,row.status,row.segment,JSON.stringify(row.roles),row.location,row.companySize,row.offer,row.notes,row.provider]);else this.campaigns.set(id,row);return row}
 async listCampaigns(context:any){const owner=this.ownerId(context);if(this.pool){const{rows}=await this.pool.query(`select id,owner_id as "ownerId",name,status,segment,roles,location,company_size as "companySize",offer,notes,provider,created_at as "createdAt",updated_at as "updatedAt" from prospector_campaigns where owner_id=$1 order by created_at desc`,[owner]);return rows}return[...this.campaigns.values()].filter(x=>x.ownerId===owner).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))}
 async addLead(context:any,input:ProspectorLeadInput){const owner=this.ownerId(context);if(!input.campaignId)throw new ProspectorError("CAMPAIGN_REQUIRED",400,"Informe a campanha.");if(!input.name?.trim()||!input.company?.trim())throw new ProspectorError("INVALID_LEAD",400,"Nome e empresa são obrigatórios.");const campaign=await this.getCampaign(context,input.campaignId);if(!campaign)throw new ProspectorError("NOT_FOUND",404,"Campanha não encontrada.");const now=new Date().toISOString(),id=randomUUID();const row={id,ownerId:owner,campaignId:input.campaignId,name:input.name.trim(),role:input.role||null,company:input.company.trim(),email:input.email||null,linkedinUrl:input.linkedinUrl||null,websiteUrl:input.websiteUrl||null,location:input.location||null,fitScore:Math.max(0,Math.min(100,Math.round(input.fitScore||0))),reason:input.reason||null,signal:input.signal||null,status:"new",source:input.source||"manual",sourceRef:input.sourceRef||null,metadata:input.metadata||{},createdAt:now,updatedAt:now};if(this.pool)await this.pool.query(`insert into prospector_leads(id,owner_id,campaign_id,name,role,company,email,linkedin_url,website_url,location,fit_score,reason,signal,status,source,source_ref,metadata) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17::jsonb)`,[id,owner,row.campaignId,row.name,row.role,row.company,row.email,row.linkedinUrl,row.websiteUrl,row.location,row.fitScore,row.reason,row.signal,row.status,row.source,row.sourceRef,JSON.stringify(row.metadata)]);else this.leads.set(id,row);return row}
 async getCampaign(context:any,id:string){const owner=this.ownerId(context);if(this.pool){const{rows}=await this.pool.query(`select id,owner_id as "ownerId",name,status,segment,roles,location,company_size as "companySize",offer,notes,provider,created_at as "createdAt",updated_at as "updatedAt" from prospector_campaigns where id=$1 and owner_id=$2`,[id,owner]);return rows[0]||null}const row=this.campaigns.get(id);return row?.ownerId===owner?row:null}
 async listLeads(context:any,campaignId:string){const owner=this.ownerId(context);if(this.pool){const{rows}=await this.pool.query(`select id,owner_id as "ownerId",campaign_id as "campaignId",name,role,company,email,linkedin_url as "linkedinUrl",website_url as "websiteUrl",location,fit_score as "fitScore",reason,signal,status,source,source_ref as "sourceRef",metadata,created_at as "createdAt",updated_at as "updatedAt" from prospector_leads where owner_id=$1 and campaign_id=$2 order by fit_score desc,created_at desc`,[owner,campaignId]);return rows}return[...this.leads.values()].filter(x=>x.ownerId===owner&&x.campaignId===campaignId).sort((a,b)=>b.fitScore-a.fitScore)}
 async updateLeadStatus(context:any,id:string,status:ProspectorLeadStatus){const owner=this.ownerId(context),allowed=["new","qualified","approved","contacted","replied","meeting","won","lost"];if(!allowed.includes(status))throw new ProspectorError("INVALID_STATUS",400,"Status inválido.");if(this.pool){const{rows}=await this.pool.query(`update prospector_leads set status=$1,updated_at=now() where id=$2 and owner_id=$3 returning id,owner_id as "ownerId",campaign_id as "campaignId",name,role,company,email,linkedin_url as "linkedinUrl",website_url as "websiteUrl",location,fit_score as "fitScore",reason,signal,status,source,source_ref as "sourceRef",metadata,created_at as "createdAt",updated_at as "updatedAt"`,[status,id,owner]);if(!rows[0])throw new ProspectorError("NOT_FOUND",404,"Lead não encontrado.");return rows[0]}const row=this.leads.get(id);if(!row||row.ownerId!==owner)throw new ProspectorError("NOT_FOUND",404,"Lead não encontrado.");row.status=status;row.updatedAt=new Date().toISOString();return row}
}