import { randomUUID } from "node:crypto";
import pg from "pg";
import type { ProspectorProvider, ProspectorDiscoveredLead } from "./prospector-provider.js";

export type ProspectorCampaignStatus="draft"|"ready"|"running"|"paused"|"completed";
export type ProspectorLeadStatus="new"|"qualified"|"approved"|"contacted"|"replied"|"meeting"|"won"|"lost";
export interface ProspectorIcpInput{name?:string;segment:string;roles:string[];location?:string;companySize?:string;offer?:string;notes?:string}
export interface ProspectorLeadInput{campaignId:string;name:string;role?:string;company:string;email?:string;linkedinUrl?:string;websiteUrl?:string;location?:string;fitScore?:number;reason?:string;signal?:string;source?:string;sourceRef?:string;metadata?:Record<string,unknown>}
export class ProspectorError extends Error{constructor(public code:string,public status:number,message:string){super(message)}}

function normalize(value:string|undefined|null){return (value||"").trim().toLowerCase()}
function scoreLead(campaign:any,lead:ProspectorDiscoveredLead){let score=35;const role=normalize(lead.role);const roles=(campaign.roles||[]) as string[];if(role&&roles.some(r=>role.includes(normalize(r))||normalize(r).includes(role)))score+=28;if(lead.email)score+=10;if(lead.linkedinUrl)score+=8;if(lead.websiteUrl)score+=6;if(lead.signal)score+=8;if(campaign.location&&lead.location&&normalize(lead.location).includes(normalize(campaign.location)))score+=5;return Math.max(0,Math.min(100,score))}

export class ProspectorService{
 private pool?:pg.Pool;public readonly storage:"postgres"|"memory";private campaigns=new Map<string,any>();private leads=new Map<string,any>();
 constructor(private options:{databaseUrl?:string;databaseSsl?:boolean;provider?:ProspectorProvider;openAiApiKey?:string;openAiTextModel?:string}){this.storage=options.databaseUrl?"postgres":"memory";if(options.databaseUrl)this.pool=new pg.Pool({connectionString:options.databaseUrl,ssl:options.databaseSsl?{rejectUnauthorized:false}:undefined})}
 get provider(){return {name:this.options.provider?.name||"manual",configured:this.options.provider?.configured??false}}
 async initialize(){if(!this.pool)return;await this.pool.query(`create table if not exists prospector_campaigns (id uuid primary key, owner_id text not null, name text not null, status text not null default 'draft', segment text not null, roles jsonb not null default '[]'::jsonb, location text, company_size text, offer text, notes text, provider text not null default 'manual', created_at timestamptz not null default now(), updated_at timestamptz not null default now())`);await this.pool.query(`create table if not exists prospector_leads (id uuid primary key, owner_id text not null, campaign_id uuid not null references prospector_campaigns(id) on delete cascade, name text not null, role text, company text not null, email text, linkedin_url text, website_url text, location text, fit_score integer not null default 0, reason text, signal text, status text not null default 'new', source text not null default 'manual', source_ref text, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now())`);await this.pool.query(`create index if not exists idx_prospector_campaigns_owner on prospector_campaigns(owner_id,created_at desc)`);await this.pool.query(`create index if not exists idx_prospector_leads_campaign on prospector_leads(campaign_id,fit_score desc,created_at desc)`)}
 async close(){await this.pool?.end()}
 private ownerId(context:any){return String(context?.organization?.id||context?.organizationId||context?.user?.id||context?.id||"unknown")}
 async createCampaign(context:any,input:ProspectorIcpInput){if(!input.segment?.trim())throw new ProspectorError("INVALID_ICP",400,"Informe o segmento do ICP.");const now=new Date().toISOString(),id=randomUUID(),owner=this.ownerId(context),name=input.name?.trim()||`ICP ${input.segment.trim()}`;const row={id,ownerId:owner,name,status:"draft",segment:input.segment.trim(),roles:(input.roles||[]).filter(Boolean),location:input.location||null,companySize:input.companySize||null,offer:input.offer||null,notes:input.notes||null,provider:this.provider.name,createdAt:now,updatedAt:now};if(this.pool)await this.pool.query(`insert into prospector_campaigns(id,owner_id,name,status,segment,roles,location,company_size,offer,notes,provider) values($1,$2,$3,$4,$5,$6::jsonb,$7,$8,$9,$10,$11)`,[id,owner,name,row.status,row.segment,JSON.stringify(row.roles),row.location,row.companySize,row.offer,row.notes,row.provider]);else this.campaigns.set(id,row);return row}
 async listCampaigns(context:any){const owner=this.ownerId(context);if(this.pool){const{rows}=await this.pool.query(`select id,owner_id as "ownerId",name,status,segment,roles,location,company_size as "companySize",offer,notes,provider,created_at as "createdAt",updated_at as "updatedAt" from prospector_campaigns where owner_id=$1 order by created_at desc`,[owner]);return rows}return[...this.campaigns.values()].filter(x=>x.ownerId===owner).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))}
 async addLead(context:any,input:ProspectorLeadInput){const owner=this.ownerId(context);if(!input.campaignId)throw new ProspectorError("CAMPAIGN_REQUIRED",400,"Informe a campanha.");if(!input.name?.trim()||!input.company?.trim())throw new ProspectorError("INVALID_LEAD",400,"Nome e empresa são obrigatórios.");const campaign=await this.getCampaign(context,input.campaignId);if(!campaign)throw new ProspectorError("NOT_FOUND",404,"Campanha não encontrada.");const now=new Date().toISOString(),id=randomUUID();const row={id,ownerId:owner,campaignId:input.campaignId,name:input.name.trim(),role:input.role||null,company:input.company.trim(),email:input.email||null,linkedinUrl:input.linkedinUrl||null,websiteUrl:input.websiteUrl||null,location:input.location||null,fitScore:Math.max(0,Math.min(100,Math.round(input.fitScore||0))),reason:input.reason||null,signal:input.signal||null,status:"new",source:input.source||"manual",sourceRef:input.sourceRef||null,metadata:input.metadata||{},createdAt:now,updatedAt:now};if(this.pool)await this.pool.query(`insert into prospector_leads(id,owner_id,campaign_id,name,role,company,email,linkedin_url,website_url,location,fit_score,reason,signal,status,source,source_ref,metadata) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17::jsonb)`,[id,owner,row.campaignId,row.name,row.role,row.company,row.email,row.linkedinUrl,row.websiteUrl,row.location,row.fitScore,row.reason,row.signal,row.status,row.source,row.sourceRef,JSON.stringify(row.metadata)]);else this.leads.set(id,row);return row}
 async getCampaign(context:any,id:string){const owner=this.ownerId(context);if(this.pool){const{rows}=await this.pool.query(`select id,owner_id as "ownerId",name,status,segment,roles,location,company_size as "companySize",offer,notes,provider,created_at as "createdAt",updated_at as "updatedAt" from prospector_campaigns where id=$1 and owner_id=$2`,[id,owner]);return rows[0]||null}const row=this.campaigns.get(id);return row?.ownerId===owner?row:null}
 async listLeads(context:any,campaignId:string){const owner=this.ownerId(context);if(this.pool){const{rows}=await this.pool.query(`select id,owner_id as "ownerId",campaign_id as "campaignId",name,role,company,email,linkedin_url as "linkedinUrl",website_url as "websiteUrl",location,fit_score as "fitScore",reason,signal,status,source,source_ref as "sourceRef",metadata,created_at as "createdAt",updated_at as "updatedAt" from prospector_leads where owner_id=$1 and campaign_id=$2 order by fit_score desc,created_at desc`,[owner,campaignId]);return rows}return[...this.leads.values()].filter(x=>x.ownerId===owner&&x.campaignId===campaignId).sort((a,b)=>b.fitScore-a.fitScore)}
 async updateLeadStatus(context:any,id:string,status:ProspectorLeadStatus){const owner=this.ownerId(context),allowed=["new","qualified","approved","contacted","replied","meeting","won","lost"];if(!allowed.includes(status))throw new ProspectorError("INVALID_STATUS",400,"Status inválido.");if(this.pool){const{rows}=await this.pool.query(`update prospector_leads set status=$1,updated_at=now() where id=$2 and owner_id=$3 returning id,owner_id as "ownerId",campaign_id as "campaignId",name,role,company,email,linkedin_url as "linkedinUrl",website_url as "websiteUrl",location,fit_score as "fitScore",reason,signal,status,source,source_ref as "sourceRef",metadata,created_at as "createdAt",updated_at as "updatedAt"`,[status,id,owner]);if(!rows[0])throw new ProspectorError("NOT_FOUND",404,"Lead não encontrado.");return rows[0]}const row=this.leads.get(id);if(!row||row.ownerId!==owner)throw new ProspectorError("NOT_FOUND",404,"Lead não encontrado.");row.status=status;row.updatedAt=new Date().toISOString();return row}
 async discover(context:any,campaignId:string,limit=20){const campaign=await this.getCampaign(context,campaignId);if(!campaign)throw new ProspectorError("NOT_FOUND",404,"Campanha não encontrada.");const provider=this.options.provider;if(!provider?.configured)throw new ProspectorError("PROVIDER_NOT_CONFIGURED",503,"O provedor de prospecção ainda não está configurado.");let found:ProspectorDiscoveredLead[];try{found=await provider.discover({segment:campaign.segment,roles:campaign.roles||[],location:campaign.location,companySize:campaign.companySize,offer:campaign.offer,limit})}catch(error){throw new ProspectorError("DISCOVERY_FAILED",502,error instanceof Error?`Falha no discovery: ${error.message}`:"Falha no discovery.")}
 const existing=await this.listLeads(context,campaignId);const keys=new Set(existing.map((x:any)=>`${normalize(x.name)}|${normalize(x.company)}`));const created=[];for(const item of found){const key=`${normalize(item.name)}|${normalize(item.company)}`;if(keys.has(key))continue;keys.add(key);created.push(await this.addLead(context,{campaignId,name:item.name,role:item.role||undefined,company:item.company,email:item.email||undefined,linkedinUrl:item.linkedinUrl||undefined,websiteUrl:item.websiteUrl||undefined,location:item.location||undefined,fitScore:scoreLead(campaign,item),reason:item.reason||`Aderência ao ICP ${campaign.segment}${item.role?` e cargo ${item.role}`:""}.`,signal:item.signal||undefined,source:provider.name,sourceRef:item.sourceRef||undefined,metadata:item.metadata||{}}))}
 if(this.pool)await this.pool.query(`update prospector_campaigns set status='ready',provider=$1,updated_at=now() where id=$2 and owner_id=$3`,[provider.name,campaignId,this.ownerId(context)]);else{campaign.status="ready";campaign.provider=provider.name;campaign.updatedAt=new Date().toISOString()}
 return {campaignId,provider:provider.name,discovered:found.length,created:created.length,leads:await this.listLeads(context,campaignId)} }
 private async getLead(context:any,id:string){const owner=this.ownerId(context);if(this.pool){const{rows}=await this.pool.query(`select id,owner_id as "ownerId",campaign_id as "campaignId",name,role,company,email,linkedin_url as "linkedinUrl",website_url as "websiteUrl",location,fit_score as "fitScore",reason,signal,status,source,source_ref as "sourceRef",metadata,created_at as "createdAt",updated_at as "updatedAt" from prospector_leads where id=$1 and owner_id=$2`,[id,owner]);return rows[0]||null}const row=this.leads.get(id);return row?.ownerId===owner?row:null}
 async prepareApproach(context:any,leadId:string,channel="email"){const lead=await this.getLead(context,leadId);if(!lead)throw new ProspectorError("NOT_FOUND",404,"Lead não encontrado.");const campaign=await this.getCampaign(context,lead.campaignId);if(!campaign)throw new ProspectorError("NOT_FOUND",404,"Campanha não encontrada.");const fallback={subject:`Ideia para ${lead.company}`,message:`Olá ${lead.name.split(" ")[0]}, vi que você atua como ${lead.role||"liderança"} na ${lead.company}. ${lead.signal?`Notei ${lead.signal}. `:""}Acredito que ${campaign.offer||"nossa solução"} pode ajudar sua operação a avançar com mais eficiência. Posso te mostrar em uma conversa rápida?`,channel};if(!this.options.openAiApiKey)return fallback;try{const response=await fetch("https://api.openai.com/v1/chat/completions",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${this.options.openAiApiKey}`},body:JSON.stringify({model:this.options.openAiTextModel||"gpt-5-mini",messages:[{role:"system",content:"Você escreve outbound B2B curto, específico, respeitoso, sem inventar fatos. Responda JSON com subject e message."},{role:"user",content:JSON.stringify({channel,lead:{name:lead.name,role:lead.role,company:lead.company,reason:lead.reason,signal:lead.signal},offer:campaign.offer,segment:campaign.segment})}],response_format:{type:"json_object"}})});if(!response.ok)return fallback;const data=await response.json() as any;const parsed=JSON.parse(data?.choices?.[0]?.message?.content||"{}");return {subject:parsed.subject||fallback.subject,message:parsed.message||fallback.message,channel}}catch{return fallback}}
}
